nodeLinker: node-modules
enableGlobalCache: true
nmMode: hardlinks-local

packageExtensions:
  react-dom@*:
    peerDependencies:
      react: "*"
  react@*:
    peerDependencies:
      react-dom: "*"
