enableGlobalCache: true

nmMode: hardlinks-local

nodeLinker: node-modules

packageExtensions:
  react-dom@*:
    peerDependencies:
      react: "*"
  react@*:
    peerDependencies:
      react-dom: "*"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
